---
- import_playbook: ../common/converge.yml

- name: Converge controller-mesh interior node config
  hosts: qdrtest
  tasks:
    - include_role:
        name: "{{ playbook_dir }}/../../../tripleo_qdr"
        tasks_from: create_config
      vars:
        qdr_connectors:
          - host: stf-default-interconnect-5671-service-telemetry.example.com
            port: 443
            role: edge
            sslProfile: sslProfile
            verifyHostname: false
        qdr_deployment_mode: controller-mesh
        controller_node_ips: "10.0.0.20,10.0.0.30,10.0.0.40,{{ ansible_default_ipv4.address }}"
        ctlplane_ip: "{{ ansible_default_ipv4.address }}"
        internal_api_ip: "{{ ansible_default_ipv4.address }}"
        service_net_map:
          controller_metrics_qdr_network: internal_api
        tripleo_role_name: Controller