---
- import_playbook: ../common/verify.yml

- name: Check log for correct config
  hosts: qdrtest
  tasks:
  - assert:
      that:
        - qdrlog_content.find('Router started in Interior mode') != -1
      success_msg: Router started in Interior mode

  - assert:
      that:
        - qdrlog_content is search('Configured Listener:.*:5668 .* role.inter-router')
      success_msg: Inter-router listener configured

  - assert:
      that:
        - qdrlog_content is search('Configured Connector: 10.0.0.20:5668 .* role=edge')
        - qdrlog_content is search('Configured Connector: 10.0.0.30:5668 .* role=edge')
        - qdrlog_content is search('Configured Connector: 10.0.0.40:5668 .* role=edge')
      success_msg: Connectors to other mesh nodes configured

  - assert:
      that:
        - qdrlog_content is search('Configured Connector: stf-default-interconnect-5671-service-telemetry.example.com:443 .* role=edge')
      success_msg: Connector to STF configured