os: linux
language: python
python: "2.7"

git:
  depth: false

# Install ansible
addons:
  apt:
    update: true
    packages:
      - python-pip

services:
  - docker

install:
  # Install ansible
  - pip install ansible ansible-lint

  # Show ansible version
  - ansible --version

script:
  - ansible-lint

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
