---
- name: Create required host directories
  file:
    mode: '{{ item.mode|default(omit) }}'
    path: '{{ item.path }}'
    setype: '{{ item.setype }}'
    state: directory
  with_items:
  - path: /var/log/containers/metrics_qdr
    setype: container_file_t
    mode: '0750'
  - path: /var/lib/metrics_qdr
    setype: container_file_t
    mode: '0750'
  - path: /var/lib/config-data/ansible-generated/metrics_qdr
    setype: container_file_t
    mode: '0750'