---

# *CS Q: There must be a way to make this a proper list in THT to skip this step here?
- name: Set the list in interior mesh nodes
  set_fact:
    interior_nodes_list: "{{ interior_nodes.split(',') }}"

- name: Configure the mesh mode settings if there are multiple interior nodes
  when: "{{ interior_nodes_list | length > 1 }}"
  block:

  # *CS TODO: metrics should have it's own network, and not use ctlplane. BZ1816046
  - name: Set interior IP for mesh mode connections to use ctlplane
    set_fact:
      interior_ip: "{{ ctlplane_ip }}"

  # *CS TODO: connect edge nodes to one or more mesh nodes. Puppet code connected to one random one, I'd prefer to connect to 2 of them
  - name: Define connectors for edge -> internal, replacing existing connectors
    when: not (interior_ip in interior_nodes_list)
    set_fact:
    # *CS TODO: Add the SSL support to mesh mode like node_base from the puppet (internal_tls), see https://github.com/openstack/puppet-tripleo/blob/432b0497f7d0d051f2b4bf34c3e841f2b97bbb44/manifests/profile/base/metrics/qdr.pp#L141
      connectors: "{{ [{
                    'host': 'TODO-pick.interior.node',
                    'port': '5668',
                    'role': 'edge',
                    'verifyHostname': 'no',
                    'saslMechanisms': 'ANONYMOUS'
                  }] }}"

  - name: Set additional listeners and connectors on interior mesh nodes
    when: interior_ip in interior_nodes_list
    block:
      - name: Set list of OTHER interior nodes with which to form mesh connections (ones with a lower ordinal position than us in the list)
        set_fact:
          mesh_connection_nodes_list: "{{ interior_nodes_list[0:interior_nodes.index(interior_ip)] }}"

      - debug:
          var: interior_nodes
      - debug:
          var: mesh_connection_nodes_list

      - name: Add extra listener for edge -> internal
        set_fact:
          # *CS TODO: Add the SSL support to mesh mode like node_base from the puppet (internal_tls), see https://github.com/openstack/puppet-tripleo/blob/432b0497f7d0d051f2b4bf34c3e841f2b97bbb44/manifests/profile/base/metrics/qdr.pp#L141
          extra_listeners:  "{{ extra_listeners + [{
                        'host': interior_ip,
                        'port': '5667',
                        'role': 'inter-router',
                        'authenticatePeer': 'no',
                        'saslMechanisms': 'ANONYMOUS'}]
                      }}"

      - name: Add mesh connections
        loop: "{{ mesh_connection_nodes_list }}"
        set_fact:
          # *CS TODO: Add the SSL support to mesh mode like node_base from the puppet (internal_tls), see https://github.com/openstack/puppet-tripleo/blob/432b0497f7d0d051f2b4bf34c3e841f2b97bbb44/manifests/profile/base/metrics/qdr.pp#L141
          connectors: "{{ connectors + [{
                        'host': item,
                        'port': '5667',
                        'role': 'inter-router',
                        'verifyHostname': 'no',
                        'saslMechanisms': 'ANONYMOUS'}]
                      }}"
# End of mesh-mode block

- name: Augment ssl_profiles with internal profile if supplied
  set_fact:
    ssl_profiles: "{{ ssl_profiles +
                     [{ 'name': 'tlsProfile',
                        'certFile': listener_ssl_cert_file,
                        'keyFile': listener_ssl_key_file,
                        'caCertFile': tripleo_internal_tlscafile
                      }] }}"
  when: tripleo_enable_internal_tls

- name: "Include QDR config role"
  block:
    - name: "Generate the qdr config files"
      include_role:
        name: qdr-config-ansible-role
      vars:
        qdr_conf_output_dir: /var/lib/config-data/ansible-generated/metrics_qdr
