---

- name: Configure the mesh mode settings if requested
  when: deployment_mode == 'controller-mesh'
  block:

  - name: Set the list in interior mesh nodes
    set_fact:
      interior_nodes_list: "{{ controller_node_ips.split(',') }}"

  # TODO(BZ1816046): metrics should have it's own network, and not use ctlplane.
  - name: Set interior IP for mesh mode connections to use ctlplane
    set_fact:
      interior_ip: "{{ ctlplane_ip }}"

  - name: Define connectors for edge -> interior, replacing existing connectors
    when: not (interior_ip in interior_nodes_list)
    block:
      - name: Remove existing connector
        set_fact:
          connectors: []

      - name: Create connectors to to two random interior nodes
        loop: "{{ (interior_nodes_list | shuffle(seed=inventory_hostname))[0:2] }}"
        set_fact:
        # *CS TODO: Add the SSL support to mesh mode like node_base from the puppet (internal_tls), see https://github.com/openstack/puppet-tripleo/blob/432b0497f7d0d051f2b4bf34c3e841f2b97bbb44/manifests/profile/base/metrics/qdr.pp#L141
          connectors: "{{ connectors + [{
                        'host': item,
                        'port': '5668',
                        'role': 'edge',
                        'verifyHostname': 'no',
                        'saslMechanisms': 'ANONYMOUS'
                      }] }}"

  - name: Set additional listeners, connectors, and mode on interior mesh nodes
    when: interior_ip in interior_nodes_list
    block:
      - name: Set mode to interior
        set_fact:
          router_mode: interior

      - name: Set list of OTHER interior nodes with which to form mesh connections (ones with a lower ordinal position than us in the list)
        set_fact:
          mesh_connection_nodes_list: "{{ interior_nodes_list[0:interior_nodes_list.index(interior_ip)] }}"

      - debug:
          var: interior_nodes_list
      - debug:
          var: mesh_connection_nodes_list

      - name: Add extra listener for edge -> interior
        set_fact:
          # *CS TODO: Add the SSL support to mesh mode like node_base from the puppet (internal_tls), see https://github.com/openstack/puppet-tripleo/blob/432b0497f7d0d051f2b4bf34c3e841f2b97bbb44/manifests/profile/base/metrics/qdr.pp#L141
          extra_listeners:  "{{ extra_listeners + [{
                        'host': interior_ip,
                        'port': '5668',
                        'role': 'inter-router',
                        'authenticatePeer': 'no',
                        'saslMechanisms': 'ANONYMOUS'}]
                      }}"

      - name: Add mesh connections
        loop: "{{ mesh_connection_nodes_list }}"
        set_fact:
          # *CS TODO: Add the SSL support to mesh mode like node_base from the puppet (internal_tls), see https://github.com/openstack/puppet-tripleo/blob/432b0497f7d0d051f2b4bf34c3e841f2b97bbb44/manifests/profile/base/metrics/qdr.pp#L141
          connectors: "{{ connectors + [{
                        'host': item,
                        'port': '5668',
                        'role': 'inter-router',
                        'verifyHostname': 'no',
                        'saslMechanisms': 'ANONYMOUS'}]
                      }}"
# End of mesh-mode block

- name: Augment ssl_profiles with internal profile if supplied
  set_fact:
    ssl_profiles: "{{ ssl_profiles +
                     [{ 'name': 'tlsProfile',
                        'certFile': listener_ssl_cert_file,
                        'keyFile': listener_ssl_key_file,
                        'caCertFile': tripleo_internal_tlscafile
                      }] }}"
  when: tripleo_enable_internal_tls

- name: "Include QDR config role"
  block:
    - name: "Generate the qdr config files"
      include_role:
        name: qdr-config-ansible-role
      vars:
        qdr_conf_output_dir: /var/lib/config-data/ansible-generated/metrics_qdr