---
###############################################################################
# NOTE: Anything that is in here is done every time you call the tripleo_role #
# This means you should add variable parsing and settings here.               #
# This should mimic the conditions section from tripleo-heat-templates        #
###############################################################################

- name: Set-up vars based on THT inputs
  debug:
    msg: "Pretending to parse vars"

# TODO - mimic this
# conditions:
#   internal_tls_enabled: {equals: [{get_param: EnableInternalTLS}, true]}
#   enable_stf: {equals: [{get_param: EnableSTF}, true]}

- name: Report what deployment stage we're at
  debug:
    msg: "This is deployment stage {{ deploy_stage }}"

###############################################################################
# TODO:  Above this line, set up the configs, and do whatever needs to be     #
# done before each stage can be run                                           #
###############################################################################

- name: Include tasks for deploy stage
  include_tasks: "{{ deploy_stage }}.yml"
