---
- name: Create host dirs for QDR
  hosts: qdrtest
  tasks:
    - name: Set defaults for testing
      set_fact:
        qdr_conf_output_dir: /etc/qpid-dispatch/
        qdr_log_output: /var/log/qdrouterd/metrics_qdr.log
