---
- name: Create host dirs for QDR
  hosts: qdrtest
  tasks:
    - include_role:
        name: "{{ playbook_dir }}/../../../tripleo-qdr-ansible-role"
        tasks_from: create_required_host_dirs

    - name: Set defaults for testing
      set_fact:
        qdr_conf_output_dir: /etc/qpid-dispatch/
        qdr_log_output: /var/log/qdrouterd/metrics_qdr.log
        qdr_ssl_profiles: [{'name': 'sslProfile'}]
