---
- name: "Create dirs that are usually volume mounted from the host"
  hosts: qdrtest
  tasks:
    - name: "Make sure that /var/log/qdrouterd exists"
      file:
        path: "/var/log/qdrouterd"
        state: directory
        owner: qdrouterd
        mode: 0755
