---
- name: Converge
  hosts: qdrtest
  tasks:
    - name: Set the variables we need that usually come from tripleo
      set_fact:
        deploy_stage: deploy_steps_tasks
        deployment_mode: edge-only
        controller_node_ips: 10.0.0.20,10.0.0.30,10.0.0.40
        ctlplane_ip: 10.0.0.10
        internal_api_ip: "{{ ansible_default_ipv4.address }}"
        service_net_map:
          standalone_metrics_qdr_network: internal_api
        tripleo_role_name: Standalone
        qdr_conf_output_dir: /etc/qpid-dispatch/

    - include_role:
        name: "{{ playbook_dir }}/../../../tripleo-qdr-ansible-role"