---
driver:
  name: ${CONTAINER_BIN:-docker}
platforms:
  - name: qdrtest
    image: quay.io/tripleomaster/openstack-qdrouterd:current-tripleo
    dockerfile: ../common/Dockerfile.j2
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../common/prepare.yml
  inventory:
    host_vars:
      qdrtest:
        qdr_conf_output_dir: /etc/qpid-dispatch/
        qdr_log_output: /var/log/qdrouterd/metrics_qdr.log

verifier:
  name: ansible

dependency:
  name: galaxy
  options:
    role-file: molecule/common/requirements.yml

scenario:
  name: internal-tls
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
    - cleanup
